Fix Husky pre-commit hook

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,1 +1,12 @@
-prettier -w .
+
+#!/bin/sh
+
+# Check if all files are formatted according to Prettier
+if npx prettier -c .; then
+    echo "All files are formatted correctly."
+    exit 0
+else
+    npx prettier --write .
+    echo "Prettier Error - There were some badly formattied files that have been properly formatted now. Please add them to your commit again."
+    exit 1
+fi
